spring.application.name=bqom

#database configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/bqom
spring.datasource.username=postgres
spring.datasource.password=welcome123
spring.datasource.driver-class-name=org.postgresql.Driver

#jpa configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true;

#Logging configuration
logging.level.root=WARN
logging.level.liquibase=INFO
logging.level.org.springframework.boot=INFO
#logging.file.name=myapp.log

#liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
#spring.liquibase.drop-first=true

#Database backup configuration
backup.directory=./backups
backup.retention.days=30
backup.pgdump.path=pg_dump

#Google Drive backup configuration
google.drive.credentials.path=/path/to/service-account-credentials.json
google.drive.folder.id=1RF87IAkXTooY7_MjaoXYnMDMh5OovCYl
